import { z } from "zod";
declare const NewPCOL: z.ZodEffects<z.ZodObject<{
    Subject: z.ZodString;
    References: z.ZodString;
    DODAAC: z.ZodString;
    Contract: z.ZodString;
    Contractor: z.ZodOptional<z.ZodString>;
    ContractorPOC: z.ZodString;
    DeliveryOrderMod: z.ZodString;
    RFI: z.ZodString;
    RFP: z.ZodString;
    ECP: z.ZodString;
    CCP: z.ZodString;
    AssociatedContractorLetterNumbers: z.ZodString;
    Disclaimers: z.ZodArray<z.ZodString, "many">;
    CarbonCopy: z.ZodString;
    AdditionalDistributionInfo: z.ZodString;
}, "strip", z.ZodTypeAny, {
    Disclaimers: string[];
    Subject: string;
    References: string;
    DODAAC: string;
    Contract: string;
    DeliveryOrderMod: string;
    RFI: string;
    RFP: string;
    ECP: string;
    CCP: string;
    AssociatedContractorLetterNumbers: string;
    CarbonCopy: string;
    AdditionalDistributionInfo: string;
    ContractorPOC: string;
    Contractor?: string | undefined;
}, {
    Disclaimers: string[];
    Subject: string;
    References: string;
    DODAAC: string;
    Contract: string;
    DeliveryOrderMod: string;
    RFI: string;
    RFP: string;
    ECP: string;
    CCP: string;
    AssociatedContractorLetterNumbers: string;
    CarbonCopy: string;
    AdditionalDistributionInfo: string;
    ContractorPOC: string;
    Contractor?: string | undefined;
}>, {
    Disclaimers: string[];
    Subject: string;
    References: string;
    DODAAC: string;
    Contract: string;
    DeliveryOrderMod: string;
    RFI: string;
    RFP: string;
    ECP: string;
    CCP: string;
    AssociatedContractorLetterNumbers: string;
    CarbonCopy: string;
    AdditionalDistributionInfo: string;
    ContractorPOC: string;
    Contractor?: string | undefined;
}, {
    Disclaimers: string[];
    Subject: string;
    References: string;
    DODAAC: string;
    Contract: string;
    DeliveryOrderMod: string;
    RFI: string;
    RFP: string;
    ECP: string;
    CCP: string;
    AssociatedContractorLetterNumbers: string;
    CarbonCopy: string;
    AdditionalDistributionInfo: string;
    ContractorPOC: string;
    Contractor?: string | undefined;
}>;
export type NewPCOL = z.infer<typeof NewPCOL>;
export {};
