import "@pnp/sp/content-types";
import "@pnp/sp/webs";
import "@pnp/sp/files";
import "@pnp/sp/folders";
export declare const useAddPCOL: (subSite: string) => import("@tanstack/react-query").UseMutationResult<any, Error, {
    Disclaimers: string[];
    Subject: string;
    References: string;
    DODAAC: string;
    Contract: string;
    DeliveryOrderMod: string;
    RFI: string;
    RFP: string;
    ECP: string;
    CCP: string;
    AssociatedContractorLetterNumbers: string;
    CarbonCopy: string;
    AdditionalDistributionInfo: string;
    ContractorPOC: string;
    Contractor?: string | undefined;
}, unknown>;
